# Generated by Django 3.2.15 on 2024-02-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='chat_room_id',
        ),
    ]
