# Generated by Django 3.2.15 on 2024-02-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20240202_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='baggage_number',
            field=models.ForeignKey(default=12345, on_delete=django.db.models.deletion.CASCADE, to='app1.postmodel'),
            preserve_default=False,
        ),
    ]
