# Generated by Django 3.2.15 on 2024-02-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_message_baggage_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default=23, max_length=1000000),
            preserve_default=False,
        ),
    ]
