# Generated by Django 3.2.15 on 2024-02-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_message_baggage_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='baggage_number',
        ),
    ]
