# Generated by Django 3.2.15 on 2024-02-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_message_baggage_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='baggage_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.room'),
        ),
    ]
